# typed: true
# frozen_string_literal: true

# Homebrew formula for Recall CLI.
#
# Generated by CI — do not edit SHA values manually.
# Platform tarballs are created by the release workflow and uploaded
# as GitHub Release assets.
#
# Repo: https://github.com/Bharath-code/recall
# Tap:  https://github.com/Bharath-code/homebrew-recall

class Recall < Formula
  desc "Local-first CLI that captures shell commands with repo context—search, project memory, and workflow detection"
  homepage "https://github.com/Bharath-code/recall"
  license "MIT"
  head "https://github.com/Bharath-code/recall.git", branch: "main"

  # ── Version ──────────────────────────────────────────────────────────
  # CI replaces this on each release. Bump manually for pre-release testing.
  version "0.1.0"

  # ── macOS (ARM) ──────────────────────────────────────────────────────
  on_macos do
    on_arm do
      url "https://github.com/Bharath-code/recall/releases/download/v#{version}/recall-v#{version}-macos-arm64.tar.gz"
      # CI: update-checksum-macos-arm64
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end

    # ── macOS (Intel) ──────────────────────────────────────────────────
    on_intel do
      url "https://github.com/Bharath-code/recall/releases/download/v#{version}/recall-v#{version}-macos-x64.tar.gz"
      # CI: update-checksum-macos-x64
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  # ── Linux (x86_64) ────────────────────────────────────────────────────
  on_linux do
    on_intel do
      url "https://github.com/Bharath-code/recall/releases/download/v#{version}/recall-v#{version}-linux-x64.tar.gz"
      # CI: update-checksum-linux-x64
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  # ── Dependencies ───────────────────────────────────────────────────────
  # Recall ships as a standalone compiled binary. No runtime dependencies.
  # Bun is only needed when building from source (--HEAD).

  # ── Install (binary release) ──────────────────────────────────────────
  def install
    bin.install "recall"
  end

  # ── Build from HEAD ─────────────────────────────────────────────────────
  head do
    depends_on "bun" => :build

    def install
      system "bun", "install", "--frozen-lockfile"
      system "bun", "build", "src/index.ts", "--compile", "--outfile", "bin/recall"
      bin.install "bin/recall"
    end
  end

  # ── Post-install message ──────────────────────────────────────────────
  def caveats
    <<~EOS
      To start using Recall, run:

        recall init

      This will guide you through shell hook installation.
      See `recall --help` for all commands.
    EOS
  end
end
